### ISSUE TITLE
Inventory Full bug

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/ExilePearl#16]
> I've been hunting raiders today, I killed REDACTED while holding 26 pearls though my inventory was full. I was under the impression that the pearl would just drop on the floor however it hasn't appeared anywhere, nor can we find it sorting through his stuff.

**Comment by CivFactions** [comment]
I can't duplicate this.
When you pearl someone and your inventory is full, the stack of pearls is dropped and the pearl is placed there instead. I tried a variety of slots.
Are we sure he actually had the pearls in his hotbar?
Can you check the logs to see if it actually tried to exile him?
