### ISSUE TITLE
Exile Bastion Placement

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/ExilePearl#24]
It is not prevented, but rather the Bastion creation is prevented, wasting the bastion if lored. Might be good to call one of the Bastion break functions, to break & drop the lored bastion so its not destroyed.

**Comment by CivFactions** [comment]
This sounds like an instance of Bastion not handling the event cancellation correctly. EP only see the create event and cancels it. Bastion should probably handle that in a smarter way.

**Comment by ProgrammerDan** [comment]
Good point, I'll review the codez unless someone beats me to it, and see what best path is indicated. Changing upstream is always dubious as refactors can inadvertently break _other_ code, but likely this is only consumer of Bastion Create. I'll do a survey.

**Comment by ProgrammerDan** [comment]
Superceded by https://github.com/DevotedMC/Bastion/issues/37
