### ISSUE TITLE
Compatibility with MythicMobs

### ISSUE THREAD

**Issue by pvprangergod** [DevotedMC/ExilePearl#25]
Hi my MythicMobs is causing ExilePearl to spam my console
Each time I hit a mob I get this message
https://pastebin.com/VRYzpV6v
Please help
Thanks

**Comment by ProgrammerDan** [comment]
What version of Mythic Mobs are you using?

**Comment by pvprangergod** [comment]
The latest version 4.1.0

**Comment by ProgrammerDan** [comment]
90% sure 4.1.0 isn't compatible with EP 1.0.0, any chance you can use latest EP too?

**Comment by pvprangergod** [comment]
Can u upload the jar for the latest ExilePearl

**Comment by ProgrammerDan** [comment]
https://github.com/DevotedMC/ExilePearl/releases/tag/1.1.0 this one?

**Comment by pvprangergod** [comment]
thanks!

**Comment by ProgrammerDan** [comment]
If that fixed it for you, feel free to close out the issue, otherwise we can keep looking :)
