### ISSUE TITLE
If a pearl is moved to the hotbar using a number key, it won't be tracked

### ISSUE THREAD

**Issue by Lazersmoke** [DevotedMC/ExilePearl#32]
The `InventoryAction` is `HOTBAR_SWAP`. https://github.com/DevotedMC/ExilePearl/blob/d06d4cb4999f4e2373245587b49649591bab99de/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java#L442

**Comment by danquist** [comment]
Can you provide the key sequence you're using to produce this?

**Comment by Lazersmoke** [comment]
Turns out this is a duplicate of #31, cause I was throwing the pearl in lava to check if it was still tracked. Could have also been #20. This tracking works as intended.
